$(function() {
    $('#activator1').click(function(){
        $('.overlay').fadeIn(300,function(){
            $('#product1').animate({'top':'50px'},500);
        });
    });
	$('#activator2').click(function(){
        $('.overlay').fadeIn('fast',function(){
            $('#product2').animate({'top':'50px'},500);
        });
    });
	$('#activator3').click(function(){
        $('.overlay').fadeIn(300,function(){
            $('#product3').animate({'top':'50px'},500);
        });
    });
	$('#activator4').click(function(){
        $('.overlay').fadeIn(300,function(){
            $('#product4').animate({'top':'50px'},500);
        });
    });
	$('#activator5').click(function(){
        $('.overlay').fadeIn(300,function(){
            $('#product5').animate({'top':'50px'},500);
        });
    });
	$('#activator6').click(function(){
        $('.overlay').fadeIn(300,function(){
            $('#product6').animate({'top':'50px'},500);
        });
    });
	$('#activator7').click(function(){
        $('.overlay').fadeIn(300,function(){
            $('#product7').animate({'top':'50px'},500);
        });
    });
	$('#activator8').click(function(){
        $('.overlay').fadeIn(300,function(){
            $('#product8').animate({'top':'50px'},500);
        });
    });
	$('#activator9').click(function(){
        $('.overlay').fadeIn(300,function(){
            $('#product9').animate({'top':'50px'},500);
        });
    });
    $('#close1').click(function(){
        $('#product1').animate({'top':'-1000px'},300,function(){
            $('.overlay').fadeOut(200);
        });
    });
	$('#close2').click(function(){
        $('#product2').animate({'top':'-1000px'},300,function(){
            $('.overlay').fadeOut(200);
        });
    });
	$('#close3').click(function(){
        $('#product3').animate({'top':'-1000px'},300,function(){
            $('.overlay').fadeOut(200);
        });
    });
	$('#close4').click(function(){
        $('#product4').animate({'top':'-1000px'},300,function(){
            $('.overlay').fadeOut(200);
        });
    });
	$('#close5').click(function(){
        $('#product5').animate({'top':'-1000px'},300,function(){
            $('.overlay').fadeOut(200);
        });
    });
	$('#close6').click(function(){
        $('#product6').animate({'top':'-1000px'},300,function(){
            $('.overlay').fadeOut(200);
        });
    });
	$('#close7').click(function(){
        $('#product7').animate({'top':'-1000px'},300,function(){
            $('.overlay').fadeOut(200);
        });
    });
	$('#close8').click(function(){
        $('#product8').animate({'top':'-1000px'},300,function(){
            $('.overlay').fadeOut(200);
        });
    });
	$('#close9').click(function(){
        $('#product9').animate({'top':'-1000px'},300,function(){
            $('.overlay').fadeOut(200);
        });
    });

});